'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("bismillahsoco.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BALIK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BALIK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blacksearch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacksearch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__10_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (10)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (11)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__12_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (12)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__13_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (13)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__14_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (14)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (15)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__21_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (21)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__22_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (22)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__23_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (23)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__24_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (24)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__28_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (28)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (8)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Desain_tanpa_judul__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Desain tanpa judul (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hapus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hapus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kembali() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kembali", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__10_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (10)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (11)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__12_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (12)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__13_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (13)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__14_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (14)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (15)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (6)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (7)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (8)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGIN__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN (9)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REGISTER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGISTER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REGISTER__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REGISTER (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sebelumnya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sebelumnya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SOCO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SOCO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tak_berjudul24_20240516143849() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tak berjudul24_20240516143849", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tambah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tambah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tamh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tamh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wishlist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wishlist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
